language: objective-c
osx_image: xcode11.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    
addons:
  ssh_known_hosts: github.com

notifications:
  email: false
  
before_install:
  - env
  - locale
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  - pod lib lint --allow-warnings

  - echo Build example
  - pod install --project-directory=Example
  - xcodebuild build -workspace Example/SDWebImagePhotosPlugin.xcworkspace -scheme SDWebImagePhotosPlugin-Example -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug | xcpretty -c

  - echo Clean DerivedData
  - rm -rf ~/Library/Developer/Xcode/DerivedData/
  - mkdir DerivedData

  - echo Run the tests
  - xcodebuild test -workspace Example/SDWebImagePhotosPlugin.xcworkspace -scheme 'SDWebImagePhotosPlugin_Tests' -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug | xcpretty -c
  - mv ~/Library/Developer/Xcode/DerivedData/ ./DerivedData/iOS

after_success:
    - bash <(curl -s https://codecov.io/bash) -D './DerivedData/iOS' -J '^SDWebImagePhotosPlugin$' -F 'iOS'